In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
bulk = pd.read_json('data/all-cards-20210329091415.json')

In [5]:
bulk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315455 entries, 0 to 315454
Data columns (total 78 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   object             315455 non-null  object
 1   id                 315455 non-null  object
 2   oracle_id          315455 non-null  object
 3   multiverse_ids     315455 non-null  object
 4   mtgo_id            31823 non-null   float64
 5   mtgo_foil_id       24254 non-null   float64
 6   tcgplayer_id       51650 non-null   float64
 7   cardmarket_id      48233 non-null   float64
 8   name               315455 non-null  object
 9   lang               315455 non-null  object
 10  released_at        315455 non-null  datetime64[ns]
 11  uri                315455 non-null  object
 12  scryfall_uri       315455 non-null  object
 13  layout             315455 non-null  object
 14  highres_image      315455 non-null  bool
 15  image_status       315455 non-null  object
 16  image_uris         313561 non-null  object
 17  mana_cost          313561 non-null  object
 18  cmc                315455 non-null  float64
 19  type_line          315455 non-null  object
 20  oracle_text        312207 non-null  object
 21  power              151718 non-null  object
 22  toughness          151718 non-null  object
 23  colors             313561 non-null  object
 24  color_identity     315455 non-null  object
 25  keywords           315455 non-null  object
 26  legalities         315455 non-null  object
 27  games              315455 non-null  object
 28  reserved           315455 non-null  bool
 29  foil               315455 non-null  bool
 30  nonfoil            315455 non-null  bool
 31  oversized          315455 non-null  bool
 32  promo              315455 non-null  bool
 33  reprint            315455 non-null  bool
 34  variation          315455 non-null  bool
 35  set                315455 non-null  object
 36  set_name           315455 non-null  object
 37  set_type           315455 non-null  object
 38  set_uri            315455 non-null  object
 39  set_search_uri     315455 non-null  object
 40  scryfall_set_uri   315455 non-null  object
 41  rulings_uri        315455 non-null  object
 42  prints_search_uri  315455 non-null  object
 43  collector_number   315455 non-null  object
 44  digital            315455 non-null  bool
 45  rarity             315455 non-null  object
 46  flavor_text        161544 non-null  object
 47  card_back_id       315455 non-null  object
 48  artist             315455 non-null  object
 49  artist_ids         315293 non-null  object
 50  illustration_id    313397 non-null  object
 51  border_color       315455 non-null  object
 52  frame              315455 non-null  object
 53  full_art           315455 non-null  bool
 54  textless           315455 non-null  bool
 55  booster            315455 non-null  bool
 56  story_spotlight    315455 non-null  bool
 57  edhrec_rank        296964 non-null  float64
 58  prices             315455 non-null  object
 59  related_uris       315455 non-null  object
 60  printed_name       243002 non-null  object
 61  printed_type_line  208328 non-null  object
 62  printed_text       196104 non-null  object
 63  all_parts          5189 non-null    object
 64  promo_types        14512 non-null   object
 65  arena_id           5755 non-null    float64
 66  loyalty            3337 non-null    object
 67  watermark          25344 non-null   object
 68  preview            4756 non-null    object
 69  frame_effects      12387 non-null   object
 70  produced_mana      41783 non-null   object
 71  card_faces         3248 non-null    object
 72  color_indicator    290 non-null     object
 73  content_warning    84 non-null      float64
 74  life_modifier      118 non-null     float64
 75  hand_modifier      118 non-null     float64
 76  variation_of       78 non-null      object
 77  flavor_name        22 non-null      object
dtypes: bool(13), datetime64[ns](1), float64(10), object(54)
memory usage: 160.3+ MB

In [3]:
english_bulk = pd.read_csv('data/en_cards.csv')

In [4]:
english_bulk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56200 entries, 0 to 56199
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      56200 non-null  int64
 1   name            56200 non-null  object
 2   lang            56200 non-null  object
 3   released_at     56200 non-null  object
 4   mana_cost       47746 non-null  object
 5   cmc             56200 non-null  float64
 6   type_line       56200 non-null  object
 7   oracle_text     53810 non-null  object
 8   power           26439 non-null  object
 9   toughness       26439 non-null  object
 10  colors          55707 non-null  object
 11  color_identity  56200 non-null  object
 12  keywords        56200 non-null  object
 13  set             56200 non-null  object
 14  rarity          56200 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 6.4+ MB

In [6]:
relevant_cols = ['name', 'released_at', 'mana_cost', 
                 'cmc', 'type_line', 'oracle_text', 'power', 'toughness', 
                 'colors', 'color_identity', 'keywords', 'set', 'rarity', 'flavor_text']

In [8]:
en_df = bulk[bulk['lang']=='en']

In [10]:
for_csv = en_df[relevant_cols]

In [11]:
for_csv.to_csv('data/en_cards.csv', index = False)

In [ ]:
type(df['mana_cost'][0])

In [5]:
categorical_cols = ['mana_cost', 'type_line', 'colors', 'color_identity', 'rarity']

In [7]:
dum_df = pd.get_dummies(english_bulk, columns = categorical_cols, drop_first = True)

In [8]:
dum_df.head(2)

,Unnamed: 0,name,lang,released_at,cmc,oracle_text,power,toughness,keywords,set,...,color_identity_['R'],"color_identity_['U', 'W']",color_identity_['U'],color_identity_['W'],color_identity_[],rarity_common,rarity_mythic,rarity_rare,rarity_special,rarity_uncommon
0,0,Fury Sliver,en,2006-10-06,6.0,All Sliver creatures have double strike.,3,3,[],tsp,...,1,0,0,0,0,0,0,0,0,1
1,1,Kor Outfitter,en,2009-10-02,2.0,"When Kor Outfitter enters the battlefield, you...",2,2,[],zen,...,0,0,0,1,0,1,0,0,0,0

In [9]:
dum_df.drop(['Unnamed: 0'], axis = 1)

,name,lang,released_at,cmc,oracle_text,power,toughness,keywords,set,mana_cost_{1000000},...,color_identity_['R'],"color_identity_['U', 'W']",color_identity_['U'],color_identity_['W'],color_identity_[],rarity_common,rarity_mythic,rarity_rare,rarity_special,rarity_uncommon
0,Fury Sliver,en,2006-10-06,6.0,All Sliver creatures have double strike.,3,3,[],tsp,0,...,1,0,0,0,0,0,0,0,0,1
1,Kor Outfitter,en,2009-10-02,2.0,"When Kor Outfitter enters the battlefield, you...",2,2,[],zen,0,...,0,0,0,1,0,1,0,0,0,0
2,Spirit,en,2015-05-22,0.0,Flying,1,1,['Flying'],tmm2,0,...,0,0,0,1,0,1,0,0,0,0
3,Siren Lookout,en,2017-09-29,3.0,Flying\nWhen Siren Lookout enters the battlefi...,1,2,"['Flying', 'Explore']",xln,0,...,0,0,1,0,0,1,0,0,0,0
4,Web,en,1994-04-01,1.0,Enchant creature (Target a creature as you cas...,NaN,NaN,['Enchant'],3ed,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56195,Hollow One,en,2020-08-13,5.0,This spell costs {2} less to cast for each car...,4,4,['Cycling'],akr,0,...,0,0,0,0,1,0,0,1,0,0
56196,Angel's Tomb,en,2015-07-17,3.0,Whenever a creature enters the battlefield und...,NaN,NaN,[],ori,0,...,0,0,0,0,1,0,0,0,0,1
56197,Celestine Reef,en,2009-09-04,0.0,Creatures without flying or islandwalk can't a...,NaN,NaN,[],phop,0,...,0,0,0,0,1,0,0,1,0,0
56198,Horned Troll,en,2003-07-28,3.0,{G}: Regenerate Horned Troll.,2,2,[],8ed,0,...,0,0,0,0,0,1,0,0,0,0
56199,Exultant Skymarcher,en,2018-01-19,3.0,Flying,2,3,['Flying'],rix,0,...,0,0,0,1,0,1,0,0,0,0

In [10]:
dum_df.to_csv('data/dum_cards.csv')